/* ==========================================================
   ELENCO PRODOTTI

   - name:  nome della fragranza
   - fam:   categoria per il filtro — deve corrispondere ESATTAMENTE
            a uno dei valori data-fam dei bottoni:
            "Women" | "Men" | "UoL"
   - desc:  breve descrizione
   - image: percorso dell'immagine in images/prodotti/
   - price: prezzo in $ (numero, senza simboli) — usato in collections.html
            per il filtro a fascia di prezzo
   ========================================================== */
const products = [
  { name:"Florale",     fam:"Women",   desc:"A luxurious, modern bouquet where the seductive warmth of night-blooming jasmine meets the delicate romance of Damask rose. Infused with a soft, velvety base of Madagascar vanilla and white musk, it leaves an elegant, powdery trail that embodies timeless femininity.", image:"images/prodotti/florale.png", price:5000 },
  { name:"Blossom Éclat",    fam:"Women", desc:"A luminous and sophisticated floral-fruity masterpiece. It opens with the crisp, sparkling sweetness of white pear and orange blossom, gently unfolding into a rich heart of absolute iris. A base of smooth praline and patchouli adds an addictive, modern touch of elegance.",       image:"images/prodotti/blossom.png", price:5000 },
  { name:"Rouge Velours",   fam:"Women",   desc:"An opulent and deeply seductive fragrance. It pairs the dark, syrupy sweetness of black cherry and roasted almond with a rich heart of crimson rose. A warm, lingering base of amberwood and tonka bean gives it a striking, nocturnal allure.",           image:"images/prodotti/Rouge.png", price:5000 },
  { name:"Orchid Nuit", fam:"Women",   desc:"An enigmatic and deeply sensual scent centered around rare black orchid and dark plum. The fragrance is sharpened by a touch of pink pepper and grounded in an earthy, luxurious base of patchouli, vetiver, and rich dark chocolate.",          image:"images/prodotti/orchid.png", price:5000 },
  { name:"Soie Blanche",      fam:"Women", desc:"The ultimate expression of clean, understated luxury. It captures the crisp sensation of white silk on the skin with notes of bright aldehydes, soft cotton flower, and powdery white iris, resting beautifully on a delicate bed of blonde woods.",               image:"images/prodotti/SoieBlanche.png", price:5000 },
  { name:"Oud Voyage",      fam:"Men",   desc:"A deep, magnetic fragrance that opens with the intense warmth of dark Cambodian Oud wood, balanced by the sharp spice of saffron and rich cardamom. The scent settles into a sophisticated base of roasted tonka bean and leather, creating a powerful, mysterious, and commanding presence.",           image:"images/prodotti/oud.png", price:5000 },
  { name:"Bleu Impérial",      fam:"Men",   desc:"A sharp, commanding scent that balances raw freshness with deep woodiness. It leads with a striking burst of cold mint and crushed pink pepper, moving swiftly into a solid heart of cedarwood and vetiver. The fragrance closes with a luxurious, lingering trace of dark incense and ambergris.",           image:"images/prodotti/bleu.png", price:5000 },
  { name:"Tabac Doré",      fam:"Men",   desc:"A rich, warm, and comforting fragrance built for the modern gentleman. It highlights the sweet, smoky aroma of premium tobacco leaves and rich Cuban rum, layered with spicy cinnamon and drizzled with warm, golden honey over a base of dark vanilla.",           image:"images/prodotti/tabac.png", price:5000 },
  { name:"Cuir Noir",      fam:"Men",   desc:"A bold, ruggedly sophisticated fragrance that celebrates ultra-premium leather. It blends the smoky texture of black suede with wild Tuscan iris and saffron, supported by a heavy, masculine backbone of dark woods, styrax, and rich frankincense.",           image:"images/prodotti/noir.png", price:5000 },
  { name:"Vert Sauvage",      fam:"Men",   desc:"A vibrant, masculine green fragrance that feels like an upscale escape into the wild. Crisp galbanum, crushed mint leaves, and bitter bergamot collide with a sharp heart of violet leaf, resting on a clean, modern base of oakmoss and mineral amber.",           image:"images/prodotti/vert.png", price:5000 },
  { name:"Atlas Meridian (Male)",      fam:"UoL",   desc:"Crisp, commanding, and deeply invigorating. Atlas Meridian pairs an intensely zesty burst of bergamot with sharp, herbal wild thyme. The fragrance evolves into a clean, architectural heart of blue cypress and smoky vetiver that cuts effortlessly through heavy summer heat.",           image:"images/prodotti/atlasmeridian.png", price:7500 },
  { name:"Obsidian Tide (Male)",      fam:"UoL",   desc:"A moody, high-contrast take on a summer scent. It contrasts the clean, ozonic chill of ocean spray with a sophisticated jolt of black pepper and mineral slate. It settles into a powerful, masculine backbone of dry cedarwood.",           image:"images/prodotti/obsidiantide.png", price:7500 },
  { name:"Velvet Horizon (Male)",      fam:"UoL",   desc:"Smooth, magnetic, and effortlessly warm. This scent opens with a juicy yet dry profile of unripe white mango spiced with crisp cardamom and pink pepper. It dries down into a sleek, golden blend of blonde woods that feels tailor-made for warm nights out.",           image:"images/prodotti/velvethorizon.png", price:7500 },
  { name:"Solstice d'Or (Female)",      fam:"UoL",   desc:"Capturing the exact moment the sun hits its peak, this fragrance opens with a radiant, effervescent burst of bright pomelo and green fig leaf. The heart unfolds with delicate, honeyed neroli blossoms, resting on a soft, sun-baked amber base that mimics warm skin at dusk.",           image:"images/prodotti/solsticedor.png", price:7500 },
  { name:"Salt & Saffron Sirens (Female)",      fam:"UoL",   desc:"An intoxicatingly coastal scent that merges the raw energy of the sea with unexpected warmth. Sharp sea salt and subtle, metallic saffron cut through a lush heart of blooming jasmine sambac, drying down into smooth, sun-bleached driftwood.",           image:"images/prodotti/saltsaffronsirens.png", price:7500 },
  { name:"Orchard Mirage (Female)",      fam:"UoL",   desc:"Refreshing and modern, this composition starts with an ultra-crisp note of iced nectarine spiked with freshly muddled mint. As the fruitiness softens, a translucent aquatic heart of water lily emerges, anchored by a sheer, breezy cashmere wood finish.",           image:"images/prodotti/orchardmirage.png", price:7500 },
  { name:"Obsidian Vapour",      fam:"Men",   desc:"Inspired by volcanic terrain and crisp high-altitude air. It features a striking opening of crushed juniper berries and iced mint, balanced by volcanic mineral slate, crisp cedar, and smoky vetiver.",           image:"images/prodotti/obsidianvapour.png", price:6000 },
  { name:"Aura Imperium",      fam:"Men",   desc:"A bold, regal scent crafted for presence. It merges spicy cardamom and dark roasted coffee beans with a rich heart of tonka bean, guided by an enduring finish of aged rum and golden amber.",           image:"images/prodotti/auraimperium.png", price:5500 },
  { name:"Verdant Drift",      fam:"Men",   desc:"Clean, grounded, and invigorating. Bright bergamot and crushed eucalyptus leaves mix with lush bamboo stem, resting gently on a fresh base of wet oakmoss and white cedarwood.",           image:"images/prodotti/verdantdrift.png", price:7000 },
  { name:"Aura Volcanique",      fam:"Men",   desc:"An intoxicating mix of charred pineapple and smoked yuzu citrus, anchored by volcanic mineral ash. A heart of spicy pink pepper gives way to dark vetiver and rich, resinous oud wood.",           image:"images/prodotti/auravolcanique.png", price:6000 },
  { name:"Verdant Tropics",      fam:"Men",   desc:"Crisp, wild green mango and crushed papaya leaves paired with sharp kaffir lime. The tropical freshness settles grounded in damp bamboo wood, vetiver root, and smoky black tea.",           image:"images/prodotti/verdant.png", price:7000 },
  { name:"Obsidian Solstice",      fam:"Men",   desc:"Bold and magnetic. Ripe spiced plum and dark passionfruit fuse with roasted Tonka bean and smoked vanilla, finished with a rich base of aged rum and dark leather.",           image:"images/prodotti/obsidianstolsice.png", price:5500 },
];

